services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: policylens-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:15
    container_name: policylens-pg
    environment:
      POSTGRES_DB: policylens
      POSTGRES_USER: policylens
      POSTGRES_PASSWORD: policylens
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  es_data:
  pg_data:
